### ISSUE TITLE
Non persistent vehicule & Price at 0

### ISSUE THREAD

**Issue by Azazelwho** [WolfkillArcadia/MarXet#1]
With Exile 1.0.2 and MarXet from Dev and Master, i have 2 problem.

First when we add a non persistent vehicule in MarXet, when we buy it, it is switched in persistent with a lock code.

Second, price for vehicule and item are good in DB but, for item in game, the price are 0, and for vehicule it's random price appear.

**Comment by WolfkillArcadia** [comment]
1. You shouldn't have been able to add non-persistent vehicles to MarXet, I have checks in place to keep you from doing that as that it will make them persistent. If you have modified the code to do this, I cannot help you. 

2. This is a feature of MarXet, it allows players to "buy back" their items that they just listed in case it was a mistake. Vehicles will cost the player who sold it a "rekeying" fee as that it will ask them for a new pin code. This price is dependent on your vehicle rekey settings in the mission file config.cpp. These are ONLY for the person who listed it, anyone else who looks at it will see the listing price.

**Comment by Azazelwho** [comment]
Hi!
Thanks for reply!
I didn't change the code, i will try again on my test server with people.
Oh! I didn't think about rekey price! Great!

Thanks!
