### ISSUE TITLE
Russian language problem

### ISSUE THREAD

**Issue by DEFAULTA3** [WolfkillArcadia/MarXet#2]
When I am using russian game language I am getting this: https://pp.vk.me/c837131/v837131358/5a24/av1_RqwJdgE.jpg
How can I fix it?

**Comment by WolfkillArcadia** [comment]
Are you talking about the name of the hat? If so, that would be an ArmA 3 translation table issue as that the name is pulled straight from the config.

**Comment by DEFAULTA3** [comment]
Yeag, I am talking about the name. It's was a font problem. For anyone who has this problem just replace OrbitronLight with RobotoRegular in RscMarXetDefines.hpp and RscMarXetDialog.hpp After this change the size of letters because it will be much smaller. Or just left it.
