### ISSUE TITLE
Spawned/VehiclesFromVirtualGarage won't save

### ISSUE THREAD

**Issue by DEFAULTA3** [WolfkillArcadia/MarXet#3]
So, after somebody put his vehicle into Virtual Garage and turn it back it can't be solled. Or if I will manually spawn vehicle it can't be solled too. Why? Here is how my VG spawns a vehicle: http://pastebin.com/jhPcKpbj
P.s. Sorry for bad english

**Comment by WolfkillArcadia** [comment]
MarXet does a check on vehicles to see if they are in a "persistent" state using the "locked" command built into ArmA. From what it looks like, unless "VirtualGarage_VehicleSpawnState" is set to 1, the vehicles never get the "lock" command applied to them therefore MarXet thinks they are non-persistent vehicles. 

Same goes for if you manually spawn a vehicle in, it has to be a "persistent" vehicle in order for MarXet to accept it as a vehicle you can list.

**Comment by DEFAULTA3** [comment]
This is the right command? https://community.bistudio.com/wiki/setVehicleLock
If no, can you tell me which script checks vehicle?

**Comment by DEFAULTA3** [comment]
Thanks, now it works. Awesome script. Will you add admin functions later? For example price changing, deleting items? Because if you delete the item in database it still will be on the MarXet before restart.

**Comment by WolfkillArcadia** [comment]
I am no longer developing MarXet, so no I will not be. 
After you change something in the database, you can force a MarXet update by running this on the server via debug console. 

`call ExileServer_MarXet_inventory_initalize;
["updateInventoryResponse",[MarXetInventory]] call ExileServer_system_network_send_broadcast;`

**Comment by DEFAULTA3** [comment]
Thank you for the answer.
